### ISSUE TITLE
遇到了一个编码问题

### ISSUE THREAD

**Issue by lovejunjie1** [wlee445/maya-dev-toolkit#1]
# TypeError: a bytes-like object is required, not 'str'
# ----------------------------------------
# ----------------------------------------
# Exception happened during processing of request from('127.0.0.1', 13354)
# Traceback (most recent call last):
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\maya\app\general\CommandPort.py", line 134, in handle
    self.wfile.write(self.server.commandMessageQueue.get() + self.resp_term)
# #   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)

请问这个问题如何能解决呀。

**Comment by mrbmp33** [comment]
Can confirm that this is an issue that also happens with maya 2024. I don't think the CommandPort.py implementation has been changed (unsure as to if this applies to maya 2025).

```
('127.0.0.1', 55853)
# ----------------------------------------
# Exception occurred during processing of request from 
# Traceback (most recent call last):
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\socketserver.py", line 747, in __init__
    self.handle()
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\site-packages\maya\app\general\CommandPort.py", line 134, in handle
    self.wfile.write(self.server.commandMessageQueue.get() + self.resp_term)
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
# TypeError: a bytes-like object is required, not 'str'
# ----------------------------------------
```

I have been tweaking the code of _C:\Program Files\Autodesk\Maya2024\Python\Lib\site-packages\maya\app\general\CommandPort.py._

Specifically this line (134):
`self.wfile.write(self.server.commandMessageQueue.get() + self.resp_term)`

and changed to this to pass it as a bytestring:
`self.wfile.write((self.server.commandMessageQueue.get() + self.resp_term).encode('utf-8'))`

as for the string to bytestrings this seemed to do the trick but for some reason there are other issues that might require opening different issue threads.

(not sure if these could relate to the same issue)
- Executing `print(__name__)` in a file in vscode will result in the value being the name of the file, not `'__main__'` as it would happen in the script editor.
- Sending the code to maya only works once-per active tab. I need to switch tabs and go back to the code in order to send the code again.

**Comment by mrbmp33** [comment]
found this which might help :)
https://github.com/artbycrunk/vscode-maya/issues/25

**Comment by wlee445** [comment]
感谢提出宝贵的建议！
问题已经在 maya 2024 中已被修复
针对 maya 2023 有两个解决办法：
1. 在 maya 中开启端口时，不要开启 `echoOutput` 
    eg : `if not cmds.commandPort(":4648",q=True):cmds.commandPort(n=":4648",stp="mel")`
2. 修改 maya `CommandPort.py` 中 134 行的代码 （ 从 maya 2024 复制）
    从 `self.wfile.write(self.server.commandMessageQueue.get() + self.resp_term))`
    至 `self.wfile.write((self.server.commandMessageQueue.get() + self.resp_term).encode())`
